sudo: required
services:
  - docker

before_install:
  - docker build -t o-sama/docker-workflow-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true o-sama/docker-workflow-practice npm run test
